---
version: 1

formatters:
  json:
    "()": __main__.JSONFormatter

handlers:
  console:
    formatter: json
    class: logging.StreamHandler
    stream: ext://sys.stdout

loggers:
  root:
    level: DEBUG
    handlers: [console]

  app:
    level: INFO
