---
version: 1
disable_existing_loggers: false

formatters:
  json:
    "()": configs.logger_formatters.JSONFormatter
  simple:
    style: "{"
    format: "{asctime} - {name} - {levelname} - {message}"

handlers:
  console:
    formatter: json
    class: logging.StreamHandler
    stream: ext://sys.stdout

  utils_handler:
    formatter: simple
    class: logging.FileHandler
    filename: logs/utils.log
    mode: w  # this mode re-creates the file every time app starts

loggers:
  root:
    level: DEBUG
    handlers: [console]

  my_app:
    level: DEBUG

  utils:
    level: DEBUG
    handlers: [utils_handler]
    propagate: false
